### ISSUE TITLE
Build script incompatible with Gradle 6

### ISSUE THREAD

**Issue by allanlewis** [mkobit/jenkins-pipeline-shared-library-example#6]
When I run any Gradle command from `master` (eef1ea2), I get the following warning:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
```
If I re-run with `--warning-mode all`, I get the following output:
```
> Configure project :
The ProjectLayout.directoryProperty() method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory.directoryProperty() method instead.
```
If I upgrade Gradle to the latest version, 5.2, I get the same warnings.

**Comment by allanlewis** [comment]
I think this is actually due to the use of that method in `mkobit/jenkins-pipeline-shared-library-example`, perhaps this issue should be moved to that repo?

**Comment by mkobit** [comment]
I believe this should be fixed by https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/pull/91 and will be released in the next version (`0.10.0`) of the plugin

**Comment by mkobit** [comment]
https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/pull/96 looks like the last one, I'll release it as `0.10.1`

**Comment by mkobit** [comment]
I think `0.10.1` has resolved this, I don't believe I see any deprecation warnings after pushing https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/commit/cd5f95c2fefa51066d4ec2292e4b659ed61e3b0b
